/**
 * IcarusFlowCommit Contract ABI
 * 
 * Generated from IcarusFlowCommit.sol
 * Used by WeilChainIcarusAdapter for contract interaction
 */

export const ICARUS_FLOW_COMMIT_ABI = [
  {
    "inputs": [
      { "internalType": "string", "name": "flowId", "type": "string" },
      { "internalType": "bytes32", "name": "workflowHash", "type": "bytes32" },
      { "internalType": "bytes32", "name": "stateRoot", "type": "bytes32" },
      { "internalType": "bytes32", "name": "auditLogHash", "type": "bytes32" },
      { "internalType": "uint256", "name": "taskCount", "type": "uint256" }
    ],
    "name": "commitWorkflow",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "flowId", "type": "string" },
      { "internalType": "bytes32", "name": "expectedHash", "type": "bytes32" }
    ],
    "name": "verifyWorkflow",
    "outputs": [
      { "internalType": "bool", "name": "valid", "type": "bool" }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "flowId", "type": "string" }
    ],
    "name": "getCommit",
    "outputs": [
      { "internalType": "bytes32", "name": "workflowHash", "type": "bytes32" },
      { "internalType": "bytes32", "name": "stateRoot", "type": "bytes32" },
      { "internalType": "bytes32", "name": "auditLogHash", "type": "bytes32" },
      { "internalType": "uint256", "name": "taskCount", "type": "uint256" },
      { "internalType": "uint256", "name": "timestamp", "type": "uint256" },
      { "internalType": "address", "name": "executor", "type": "address" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "flowId", "type": "string" }
    ],
    "name": "exists",
    "outputs": [
      { "internalType": "bool", "name": "", "type": "bool" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getTotalCommits",
    "outputs": [
      { "internalType": "uint256", "name": "", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "uint256", "name": "index", "type": "uint256" }
    ],
    "name": "getFlowIdAtIndex",
    "outputs": [
      { "internalType": "string", "name": "", "type": "string" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "string", "name": "flowId", "type": "string" },
      { "indexed": false, "internalType": "bytes32", "name": "workflowHash", "type": "bytes32" },
      { "indexed": false, "internalType": "bytes32", "name": "stateRoot", "type": "bytes32" },
      { "indexed": false, "internalType": "bytes32", "name": "auditLogHash", "type": "bytes32" },
      { "indexed": false, "internalType": "uint256", "name": "taskCount", "type": "uint256" },
      { "indexed": false, "internalType": "address", "name": "executor", "type": "address" },
      { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }
    ],
    "name": "WorkflowCommitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "string", "name": "flowId", "type": "string" },
      { "indexed": false, "internalType": "bool", "name": "valid", "type": "bool" },
      { "indexed": false, "internalType": "address", "name": "verifier", "type": "address" },
      { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }
    ],
    "name": "WorkflowVerified",
    "type": "event"
  }
] as const;

// Bytecode placeholder - would be generated by Solidity compiler
// In production, deploy the contract and use the deployed bytecode
export const ICARUS_FLOW_COMMIT_BYTECODE = "0x608060405234801561..."; // Truncated for readability
